config/routes.rb
Bidder::Application.routes.draw do
  resources :categories

  resources :bids

  get 'my_jobs' => 'my_jobs#index'
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end  
  
  resources :users
  resources :jobs

  root 'jobs#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set
  has_many :jobs, -> { order(updated_at: :desc) }

  validates :title, presence: true


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:index, :edit, :new, :create, :update, :destroy]
  skip_before_action :authorize, only: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:rgt)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    if @category.parent_id == nil
      @category.parent_id = @category.id
    end



    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.title}" }, prompt: 'Select a category parent' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Parent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= if category.parent then category.parent.title end %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @category.parent %>
</p>

<% cache ['jobs', Job.latest] do %>
  <table>
    <thead>
      <!--<tr>
        <th>Title</th>
        <th>Description</th>
        <th>Image url</th>
        <th>Category</th>
        <th>Status</th>
        <th>From</th>
        <th>To</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>-->
    </thead>
    <tbody>      
      <% @category.jobs.each do |job| %>
        <% cache ['entry', job] do %>
          <div class="entry">
            <tr class="<%= cycle('list_line_odd','list_line_even') %>">
              <td>
                <%= image_tag(job.image_url, class: 'list_image') %>
              </td>

              <td class="list_description">
                <dl>
                  <dt><%= link_to job.title, job %></dt>
                  <dd>
                    <%= truncate(strip_tags(job.description), length: 80) %>
                  </dd>
                  <dd class="date">
                    <b>From:</b> <%= job.from %>
                  </dd>
                  <dd class="date">
                    <b>To:</b> <%= job.to %>
                  </dd>
                </dl>
              </td>     
              <td class="list_actions">
                <%= link_to 'Show', job %>
                <% if session[:user_id] %>
                  <% if User.find_by(id: session[:user_id]).access == 'administrator' || job.user_id == session[:user_id] %>
                    <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?'} %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          </div>
        <% end %>
      <% end %>       
    </tbody>
  </table>
<% end %> 
<br>

<%= link_to 'New Job', new_job_path %>